accounts/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Administrator'
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^active/(?P<active_code>\w+)/$', views.active, name='active'),
                       url(r'^send_active_email/(?P<user_id>\w+)/$', views.send_active_email, name='re_active'),
                       url(r'^login/$', views.login, name='login'),
                       url(r'^logout/$', views.logout, name='logout'),
                       url(r'^check_detail/$', views.check_detail, name='check_detail'),
                       url(r'^reset_password/$', views.reset_password, name='reset_password'),
)

liyan/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import django_databrowse

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'liyan.views.home', name='home'),
                       # url(r'^liyan/', include('liyan.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^accounts/',  include('accounts.urls', namespace="accounts")),
                       url(r'^msg_bd/',  include('msg_bd.urls', namespace="msg_bd")),

                       #  默认首页
                       url(r'^$',  'accounts.views.index'),
                       )

accounts/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.db import models
from django.utils import timezone
# import django_databrowse

class UserManager(BaseUserManager):
    def create_user(self, email, username, password):
        if not email or not username or not password:
            raise ValueError('Users must have an email address, a username and a password')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            create_time=timezone.now(),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password, **extra_fields):
        u = self.create_user(username, email, password, **extra_fields)
        u.is_staff = True
        u.is_active = True
        u.is_superuser = True
        u.save(using=self._db)
        return u


class User(AbstractBaseUser):
    username = models.CharField(max_length=200, db_index=True, verbose_name='username')
    email = models.EmailField(max_length=200, unique=True, db_index=True, verbose_name='email')
    create_time = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=False)
    active_code = models.CharField(max_length=500)
    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __unicode__(self):
        return self.username + "-" + self.email

# django_databrowse.site.register(User)

accounts/views.py
# -*- coding: utf-8 -*-
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db import transaction
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.views.decorators.csrf import csrf_exempt

from liyan.settings import DOMAIN
from liyan.settings import site_name
from liyan.settings import NEED_CONFIRM_EMAIL
from helper.utils import send_email
from helper.utils import generate_register_code
from models import User


@csrf_exempt
@transaction.commit_manually
def register(request):
    if 'username' in request.POST and 'password' in request.POST and 'email' in request.POST:
        # 已经有数据从前端传回来，用户已填写表单注册
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        try:
            new_user = User.objects.create_user(email, username, password)
            active_code = generate_register_code(new_user.id)

            new_user.active_code = active_code
            if not NEED_CONFIRM_EMAIL:
                new_user.is_active = True
            new_user.save()

            url = reverse('accounts:login')
            transaction.commit()
            # 数据库操作成功，事务递交
            return HttpResponseRedirect(url)
        except Exception, e:
            print e
            transaction.rollback()
            # 数据库操作失败，事务回滚
            # 这里继续回到注册页面，并将用户已经填写的非敏感信息返回到前端，方式信息重复填写
            return render_to_response("accounts/register.html",
                                      {'username': username, 'email': email},
                                      context_instance=RequestContext(request))

    else:
        # 尚无数据传回，用户刚打开注册页面
        transaction.rollback()
        # 数据库操作失败，事务回滚
        return render_to_response("accounts/register.html",
                                  context_instance=RequestContext(request))


def active(request, active_code):
    try:
        new_user = User.objects.get(active_code=active_code)
        new_user.is_active = True
        new_user.save()
        return HttpResponseRedirect(reverse('accounts:login'))
    except Exception, e:
        print e
        return render_to_response("accounts/active.html",
                                  {'error': '激活码错误，请重新注册'},
                                  context_instance=RequestContext(request))


@csrf_exempt
def login(request):
    if 'email' in request.POST and 'password' in request.POST:
        # 前台通过POST方式传回username与password两个参数
        email = request.POST.get('email', '')
        password = request.POST.get('password', '')
        # 这里的认证需要的参数username通过setting.py里的AUTH_USER_MODEL进行设置
        user = auth.authenticate(email=email, password=password)
        # 认证成功则登录，使用django自带的login
        if user is not None:
            if not user.is_active:
                active_url = reverse('accounts:re_active', kwargs={'user_id': user.id})
                return render_to_response("accounts/login.html",
                                          {'email': email,
                                           'error': "账户尚未激活，请激活后登陆",
                                           'resend_active_email': active_url},
                                          context_instance=RequestContext(request))
            auth.login(request, user)
            url = reverse("accounts:index")
            return HttpResponseRedirect(url)
        else:
            return render_to_response("accounts/login.html", {'email': email,
                                                              'error': "账户名或密码错误"})
    else:
        return render_to_response("accounts/login.html",
                                  context_instance=RequestContext(request))


def send_active_email(request, user_id):
    try:
        user = User.objects.get(id=user_id)
        active_code = user.active_code
        active_url = reverse('accounts:active', kwargs={'active_code': active_code})
        send_email("账户激活", "欢迎注册" + site_name + "点击以下链接激活账户" + DOMAIN + active_url, user.email)
        return render_to_response('accounts/re_active.html',
                                  {'error': 0,
                                   'msg': "激活邮件已重新发送直您的邮箱"
                                          + user.email.decode('ascii').encode("utf-8") +
                                          "，请注意查收"},
                                  context_instance=RequestContext(request))
    except User.DoesNotExist:
        return render_to_response('accounts/re_active.html',
                                  {'error': 0,
                                   'error_msg': "用户不存在，请先注册"},
                                  context_instance=RequestContext(request))
    except Exception, e:
        print e
        return render_to_response('accounts/re_active.html',
                                  {'error': 0,
                                   'error_msg': "数据库错误，请重试"},
                                  context_instance=RequestContext(request))


def index(request):
    ret = {}
    if request.user is not None:
        ret['username'] = request.user.username
    return render_to_response("accounts/index.html",
                              ret,
                              context_instance=RequestContext(request))


def logout(request):
    auth.logout(request)
    # 退出后直接重定向到首页
    url = reverse('accounts:index')
    return HttpResponseRedirect(url)


@csrf_exempt
@login_required()
def check_detail(request):
    if 'username' in request.POST:
        username = request.POST.get('username')
        user = User.objects.get(id=request.user.id)
        user.username = username
        user.save()
        return HttpResponseRedirect("/accounts/")
    else:
        username = request.user.username
        email = request.user.email
        create_time = request.user.create_time
        return render_to_response("accounts/detail.html",
                                  {'username': username,
                                   'email': email,
                                   'create_time': create_time.strftime('%Y-%m-%d'), },
                                  context_instance=RequestContext(request))


@csrf_exempt
@login_required()
def reset_password(request):
    if 'new_password' in request.POST and 'old_password' in request.POST:
        if request.user.check_password(request.POST.get("old_password")):
            request.user.set_password(request.POST.get("new_password"))
            request.user.save()
            return logout(request)
        else:
            return render_to_response("accounts/reset_password.html",
                                      {'error': "旧密码不符"},
                                      context_instance=RequestContext(request))
    else:
        return render_to_response("accounts/reset_password.html",
                                  context_instance=RequestContext(request))

accounts/templates/accounts/active.html
{% extends "base.html" %}

{% block content %}

    <div class="alert alert-danger">
        {% if error %}
            <p>{{ error }}</p>
        {% endif %}
    </div>


{% endblock %}

accounts/templates/accounts/detail.html
{% extends "base.html" %}

{% block content %}


    <form action="" method="post" class="form-detail">
    <h2 class="form-detail-heading">您好，{{ username }}</h2>

        <label for="username">User name:</label>
        <input class="form-control" type="text" name="username" value="{{ username }}" id="username">

        <br>

        <label for="email">Email:</label>
        <input class="form-control" type="text" name="email" value="{{ email }}" id="username" disabled>

        <br>

        <label for="create_time">Create time:</label>
        <input class="form-control" type="text" name="create_time" value="{{ create_time }}" id="username" disabled>

        <br>

        <input type="submit" class="btn btn-primary btn-lg" value="change username" />
        <a id="reset_password" class="btn btn-primary btn-lg" href="{% url 'accounts:reset_password' %}">reset password</a>
    </form>



{% endblock %}

accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block content %}
    <div class="container text-center">

        <div class="container">
            <h1>
                {% if username %}
                    {{ username }}
                {% else %}
                    游客
                {% endif %}，欢迎来到{{ site_name }}！
            </h1>

            {% if username %}
                <a id="check_detail" href="{% url 'accounts:check_detail' %}" type="button" class="btn btn-primary btn-lg">My Account</a>
                <a id="logout" href="{% url 'accounts:logout' %}" type="button" class="btn btn-default btn-lg">Logout</a>
            {% else %}
                <a id="login" href="{% url 'accounts:login' %}" type="button" class="btn btn-primary btn-lg">Login</a>
                <a id="register" href="{% url 'accounts:register' %}" type="button" class="btn btn-default btn-lg">Sign Up</a>
            {% endif %}
        </div>


    </div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

        <form action="" method="post" class="form-signin" role="form">
            <h2 class="form-signin-heading">Please sign in</h2>
            <label for="email">Email:</label>
            <input class="form-control" type="text" name="email" value="{{ email }}" id="email">
            <br>
            <label for="password">Password:</label>
            <input class="form-control" type="password" name="password" value="" id="password">
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
            </label>
            <br>
            {% if error %}
                <p class="error">{{ error }}</p>
            {% endif %}
            {% if resend_active_email %}
                <p class="error">点击<a href="{{ resend_active_email }}">这里</a>重新发送激活邮件</p>
            {% endif %}
            <input class="btn btn-lg btn-primary btn-block" type="submit" value="login"/>
        </form>


{% endblock %}

accounts/templates/accounts/re_active.html
{% extends "base.html" %}

{% block content %}
    <div class="alert alert-info">{% if error %}
        <span>{{ error_msg }}</span>
    {% else %}
        <span>{{ msg }}</span>
    {% endif %}</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <form action="" method="post" class="form-signup" role="form">
            <h2 class="form-signup-heading">Please sign up</h2>

            <label for="username">User name:</label>
            <input class="form-control" type="text" name="username" value="{{ username }}" id="username">

            <br>

            <label for="email">Email:</label>
            <input class="form-control" type="email" name="email" value="{{ email }}" id="email">
            <br>

            <label for="password">Password:</label>
            <input class="form-control" type="password" name="password" value="" id="password">

            <br>
            <input type="submit" value="register" class="btn btn-lg btn-primary btn-block"/>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends "base.html" %}

{% block content %}

    <form action="" method="post" class="form-signup">
        <label for="old_password">Old Password:</label>
        <input class="form-control" type="password" name="old_password" value="" id="old_password">

        <br>

        <label for="new_password">Password:</label>
        <input class="form-control" type="password" name="new_password" value="" id="new_password">

        <br>

        {% if error %}
            <p class="error">{{ error }}</p>
        {% endif %}
        <input type="submit" class="btn btn-primary btn-lg" value="reset_password" />
    </form>

{% endblock %}