liyan/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import django_databrowse

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'liyan.views.home', name='home'),
                       # url(r'^liyan/', include('liyan.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^accounts/',  include('accounts.urls', namespace="accounts")),
                       url(r'^msg_bd/',  include('msg_bd.urls', namespace="msg_bd")),

                       #  默认首页
                       url(r'^$',  'accounts.views.index'),
                       )

msg_bd/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Administrator'
from django.conf.urls import patterns, url
from msg_bd import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^new_msg', views.new_msg, name='new_msg'),
                       url(r'^get_msg', views.get_msg, name='get_msg'),
                       url(r'^reply_msg', views.reply_msg, name='reply'),
                       url(r'^delete_msg', views.delete_msg, name='delete_msg'),

)

msg_bd/models.py
from django.db import models
# import django_databrowse


class Msg(models.Model):
    user_name = models.CharField(max_length=200, default='Anonymous')
    user = models.ForeignKey('accounts.User', blank=True, null=True)
    contact_email = models.EmailField()
    create_time = models.DateTimeField(auto_now_add=True)
    TYPE_CHOICE = (
        ('0', 'message'),
        ('1', 'reply'),
    )
    msg_type = models.IntegerField(default=0)
    has_reply = models.BooleanField(default=False)
    msg_reply_to = models.ForeignKey('Msg', blank=True, null=True)
    content = models.CharField(max_length=2000)

    def __unicode__(self):
        return self.user_name + ":" + self.content

# django_databrowse.site.register(Msg)

msg_bd/views.py
# -*- coding: utf-8 -*-
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db import transaction
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.views.decorators.csrf import csrf_exempt

from liyan.settings import DOMAIN
from helper.utils import send_email
from helper.utils import json_response
from models import Msg


def index(request):
    ret = {}
    if request.user.is_authenticated():
        ret['username'] = request.user.username
        return render_to_response("msg_bd/index.html",
                                  ret,
                                  context_instance=RequestContext(request))
    return render_to_response("msg_bd/index.html",
                              ret,
                              context_instance=RequestContext(request))


@csrf_exempt
def new_msg(request):
    if 'content' in request.POST and 'contact_email' in request.POST:
        msg = Msg(content=request.POST.get('content'), contact_email=request.POST.get('contact_email'))
        if request.user.is_authenticated():
            msg.user = request.user
            msg.user_name = request.user.username
        msg.save()
        ret = {
            'content': msg.content,
            'contact_email': msg.contact_email,
            'create_time': msg.create_time.strftime("%Y-%m-%d"),
            'user_name': msg.user_name,
            'msg_id': msg.id,
        }
        return json_response(True, '0', 'success', ret)
    else:
        return json_response(False, '020001', 'lack of parameter')


def get_msg(request):
    msgs = Msg.objects.all()
    ret = []
    for msg in msgs:
        item = {
            'user_name': msg.user_name,
            'contact_email': msg.contact_email,
            'create_time': msg.create_time.strftime("%Y-%m-%d"),
            'content': msg.content,
            'msg_id': msg.id,
        }
        ret.append(item)
    return json_response(True, '0', 'success', ret)


@csrf_exempt
def reply_msg(request):
    if not 'reply_content' in request.POST and not 'reply_user' in request.POST and not 'msg_id' in request.POST and \
            not 'email' in request.POST:
        return json_response(False, '020002', 'lack of parameter')
    try:
        msg = Msg.objects.get(id=request.POST.get("msg_id"))
        reply = Msg(contact_email=request.POST.get("email"), content=request.POST.get('reply_content'), msg_type=1,
                    msg_reply_to=msg)
        msg.has_reply = True
        msg.save()
        if request.user.is_authenticated():
            reply.user = request.user
            reply.user_name = request.user.username
        reply.save()
        ret = {
            'content': reply.content,
            'contact_email': reply.contact_email,
            'create_time': reply.create_time.strftime("%Y-%m-%d"),
            'user_name': reply.user_name,
            'msg_id': reply.id,
            'reply_to_msg': msg.id,
        }
        return json_response(True, '0', 'success', ret)
    except Msg.DoesNotExist:
        return json_response(False, '020003', '留言不存在')
    except Exception, e:
        print e
        return json_response(False, '020004', '数据库错误')


@csrf_exempt
def delete_msg(request):
    # TODO check user type
    if 'msg_id' not in request.POST:
        return json_response(False, '020003', 'lack of parameter')
    try:
        msg = Msg.objects.get(id=request.POST.get("msg_id"))
        msg.delete()
        return json_response(True, '0', 'success')
    except Msg.DoesNotExist:
        return json_response(False, '020005', "msg does not exist")
    except Exception, e:
        print e
        return json_response(False, '020006', '数据库错误')

msg_bd/templates/msg_bd/index.html
{% extends "base.html" %}

{% block content %}
    <h1>
        {% if username %}
            {{ username }}
        {% else %}
            游客
        {% endif %}，欢迎来到{{ site_name }}留言板！
    </h1>
    <table id="msg_bd" border="1">
        <thead>
        <tr>
            <td class="table_narrow">Name</td>
            <td class="table_narrow">Time</td>
            <td class="table_narrow">Email</td>
            <td class="table_wide">Content</td>
            <td class="table_wide">Reply</td>
            <td class="table_wide">Op</td>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
    <label for="new_msg">New Msg:</label>
    <br>
    <textarea id="new_msg" style="width: 800px;"></textarea>
    <br>
    <label for="email">Contact Email:</label>
    <br>
    <input type="email" name="email" value="{{ user.email }}" id="email">
    <input id="post_new_msg" type="button" value="留言"/>
    <input id="post_new_msg_cancel" type="button" value="重置"/>
    <input id="reply_msg" type="button" value="回复" style="display: none;"/>
    <input id="reply_msg_cancel" type="button" value="取消" style="display: none;"/>
    <br>
{% endblock %}
{% block head_js %}
    <script type="text/javascript">
        // 这句表示js代码在页面加载完毕后执行，所有需要执行的函数均放在$(function () {}里面
        $(function () {
            get_msg();
            post_new_msg();
            button_visibility_toggle();
            delete_msg();
        });

        function delete_msg() {
            // when using delegate like this, we don't need to put this function after the DOM is appended
            $(document).delegate(".msg_delete", "click", function () {
                // confirm() return true when user click yes or false otherwise
                if (!confirm("Are you sure you want to delete this msg?")) {
                    return;
                }
                var msg_id = $(this).parent(1).attr("msg-id");
                $.ajax({
                    type: "POST",
                    url: "{% url 'msg_bd:delete_msg' %}",
                    data: {msg_id:msg_id},
                    dataType: "json",
                    success: function(){
                        location.reload();
                    }
                });
            });
        }

        function reply() {
            $('.msg_reply').click(function () {
                // 获取该条记录的msg的id
                var msg_id = $(this).parent(1).attr("msg-id");
                var msg_username = $(this).parent(1).children('td:first').text();
                $('#new_msg').val("reply to " + msg_username + ":").focus();
                {% if username %}
                    $('#email').val({{ request.user.email }});
                {% endif %}
                button_visibility_toggle("new");
                // 把该id，连通回复的相关内容，传回后台
                reply_msg(msg_id);
            })
        }

        function reply_msg(msg_id) {
            $('#reply_msg').click(function () {
                var email = $('#email').val();
                var content = $('#new_msg').val();
                // 检查留言信息是否完整，不完整则提醒用户，并使当前函数返回
                if (email == "" || content == "") {
                    alert("请填写完整的留言信息！");
                    return;
                }
                $.post("{% url 'msg_bd:reply' %}", {reply_content: content, email: email, msg_id: msg_id },
                        function (response) {
                            if (response['flag'] == true) {
                                alert(response['msg']);
                                // TODO
                            }
                        }, 'json')
            })
        }

        function post_new_msg() {
            // 这句表示当留言的按钮被点击时需要执行的动作
            $('#post_new_msg').click(function () {
                var email = $('#email').val();
                var content = $('#new_msg').val();
                // 检查留言信息是否完整，不完整则提醒用户，并使当前函数返回
                if (email == "" || content == "") {
                    alert("请填写完整的留言信息！");
                    return;
                }
                $.ajax({
                    type: "POST",   // 数据交换方式，如果递交的数据要修改后台数据库，则此处必须选择POST，反之为GET
                    url: '{% url 'msg_bd:new_msg' %}',  // 处理递交的数据的后台函数
                    data: {content: content, contact_email: email}, // 递交的具体数据，使用key: value的方式传递
                    success: function (response) {  // 处理完数据后前台的回调函数（即后台执行完之后前台接着要做的事）
                        if (response['flag'] == true) {
                            var data = response['data'];
                            // 拼接页面元素
                            var html = concatenate_msg_html(data);
                            // 将拼接好的页面元素贴到页面中
                            $("#msg_bd").append(html);
                            // 清空输入框，方便再一次输入
                            $('#new_msg').val('');
                            $('#email').val('')
                        } else {
                            alert(response['msg'])
                        }
                        reply();
                    },
                    dataType: 'json'
                });
            })
        }

        function get_msg() {
            // 这是异步请求的另一种写法，这里也可以使用上面的ajax来写，并把type参数置为get，基本原理同上
            $.getJSON("{% url 'msg_bd:get_msg' %}", function (response) {
                if (response['flag'] == true) {
                    var data = response['data'];
                    var html = "";
                    for (var i = 0; i < data.length; i++) {
                        var msg = data[i];
                        var single_msg = concatenate_msg_html(msg);
                        html = html + single_msg;
                    }
                    $("#msg_bd").append(html);
                }
                reply();
            })
        }

        function concatenate_msg_html(msg) {
            return "<tr msg-id=" + msg['msg_id'] + "><td>" + msg['user_name'] + "</td><td>" + msg['create_time'] +
                    "</td><td>" + msg['contact_email'] + "</td><td>" + msg['content'] + "</td><td class='msg_reply'>" +
                    "<button>回复</button></td><td class='msg_delete'><button>删除</button></td></tr>";
        }

        function button_visibility_toggle(current) {
            current = current || "";
            if (current == "new") {
                $('#reply_msg').show();
                $('#reply_msg_cancel').show();
                $('#post_new_msg').hide();
                $('#post_new_msg_cancel').hide();
            } else if (current == "reply") {
                $('#reply_msg').hide();
                $('#reply_msg_cancel').hide();
                $('#post_new_msg').show();
                $('#post_new_msg_cancel').show();
            } else {
                // click the reply cancel button will clear the msg content and email and change
                // button back to post new one
                $('#reply_msg_cancel').click(function () {
                    $('#email').val("");
                    $('#new_msg').val("");
                    button_visibility_toggle("reply");
                })
                // click post new cancel just clear content and email
                $('#post_new_msg_cancel').click(function () {
                    $('#email').val("");
                    $('#new_msg').val("");
                })
            }
        }
    </script>
{% endblock %}