liyan/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import django_databrowse

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'liyan.views.home', name='home'),
                       # url(r'^liyan/', include('liyan.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^accounts/',  include('accounts.urls', namespace="accounts")),
                       url(r'^msg_bd/',  include('msg_bd.urls', namespace="msg_bd")),

                       #  默认首页
                       url(r'^$',  'accounts.views.index'),
                       )

msg_bd/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Administrator'
from django.conf.urls import patterns, url
from msg_bd import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^new_msg', views.new_msg, name='new_msg'),
                       url(r'^get_msg', views.get_msg, name='get_msg'),
                       url(r'^reply_msg', views.reply_msg, name='reply'),
                       url(r'^delete_msg', views.delete_msg, name='delete_msg'),

)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <META http-equiv="Content-Script-Type" content="text/javascript">
    <script type="text/javascript" src="/static/media/js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="/static/media/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/media/css/site.css">
    <link rel="stylesheet" type="text/css" href="/static/media/css/bootstrap.css">
    <title>
        {% block title %}
            {{ site_name }}
        {% endblock %}
    </title>
    {% block head_js %}
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="navbar navbar-inverse navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">{{ site_name }}</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'accounts:index' %}">Home</a></li>
                    <li><a href="{% url 'msg_bd:index' %}">MsgBoard</a></li>
                </ul>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>